project:
  type: website

website:
  title: "Reid Shaw"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - cv.qmd

format:
  html:
    fontawesome: true
    theme: 
      light: sandstone
      dark: cyborg
    css: styles.css
    toc: true